# Generated by Django 5.1.1 on 2024-09-26 13:56

import url_management.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='id',
            field=models.CharField(default=url_management.utils.shortend_url_object_id_generator, max_length=24, primary_key=True, serialize=False, unique=True),
        ),
    ]
