# Generated by Django 5.1.1 on 2024-09-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_management', '0002_alter_shortenedurl_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedurl',
            name='shortened_url',
        ),
    ]
